FROM selenium/standalone-chrome

USER root

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y  software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get -y install openjdk-8-jdk && \
    apt-get clean

ENV CHROME_DRIVER /usr/bin/chromedriver

RUN mkdir /opt/dora-tests
ADD dora-tests.jar /opt/dora-tests/dora-tests.jar
ADD resources /opt/dora-tests/resources
ADD config /opt/dora-tests/src/test/resources/config
ADD entrypoint.sh /opt/dora-tests/
RUN chmod +x /opt/dora-tests/entrypoint.sh
WORKDIR /opt/dora-tests

CMD ["/opt/dora-tests/entrypoint.sh"]
