FROM cwds/javajdk

RUN yum -y install curl
RUN curl https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip -o /usr/local/bin/chromedriver
RUN chmod +x /usr/local/bin/chromedriver

RUN mkdir /opt/dora-tests
ADD dora-tests.jar /opt/dora-tests/dora-tests.jar
ADD resources /opt/dora-tests/resources
ADD config /opt/dora-tests/src/test/resources/config
ADD entrypoint.sh /opt/dora-tests/
RUN chmod +x /opt/dora-tests/entrypoint.sh
WORKDIR /opt/dora-tests

ENV CHROME_DRIVER="/usr/local/bin/chromedriver"

CMD ["/opt/dora-tests/entrypoint.sh"]
