applicationName: CWDS Dora

shiro:
  iniConfigs: ["file:${SHIRO_CONFIG_PATH:-config/shiro_nosec.ini}"]
  
swagger:
  templateName: swagger.mustache
  assetsPath: /static
  resourcePackage: gov.ca.cwds.rest.resources
  title: CWDS Dora
  description: RESTful search services for the CWS New System.
  logo: images/CWDS-API-Logo-Horizontal.png
  loginUrl: ${PERRY_URL:-http://localhost:8090/authn/login}
  showSwagger: ${SHOW_SWAGGER:-false}
  jsonUrl: ${SWAGGER_JSON_URL:-http://localhost:8080/swagger.json}
  callbackUrl: ${SWAGGER_CALLBACK_URL:-http://localhost:8080/swagger}

mode: ${DORA_MODE:-PROD}

elasticsearch:
  nodes: ${ES_NODES:-dora.dev.cwds.io:9200,localhost:9210}
  user: ${XPACK_USER:-elastic}
  password: ${XPACK_PASSWORD:-changeme}
  xpack:
    enabled: ${XPACK_ENABLED:-true}

server:
  applicationConnectors:
  - type: http 
    port: ${APP_STD_PORT:-8080}
  adminConnectors:
  - type: http
    port: ${APP_ADMIN_PORT:-8081}
    
  requestLog:
    appenders:
      - type: console

sundial:
  thread-pool-size: 10
  shutdown-on-unload: true
  wait-on-shutdown: false
  start-delay-seconds: 0
  start-scheduler-on-load: true
  global-lock-on-load: false
  tasks: [startjob, stopjob, addcronjobtrigger]

logging:
  level: ${LOGLEVEL:-WARN}
  loggers:
    "AUDIT":
      level: ALL
    "gov.ca.cwds":
      level: DEBUG
  appenders:
    - type: console
      threshold: WARN
      timeZone: UTC
      target: stdout
      logFormat: '%X{remoteAddress} [%date{ISO8601}] %level "%thread" "%X{uniqueId}" %logger: "%message%n"'

version: -UNUSED-
